config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  namespace :admin do
    root "home#index"
    resources :products
    resources :checkouts
    resources :orders
    resources :users
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users
  resources :products do
    resources :reviews
  end
  resources :orders, only: %i[create update destroy]
  resources :line_items, only: %i[create update destroy]
  resources :checkouts, param: :slug
  resource  :cart, only: [:show]
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

module Admin
  class HomeController < ApplicationController
    def index
      cards_information
      tables_information
      chart_information
    end

    private

    def cards_information
      @user_count = User.count
      @product_count = Product.count
      @order_count = Checkout.count
    end

    def tables_information
      @checkouts = Checkout.last(5)
      @users = User.last(5)
      @products = Product.last(5)
    end

    def chart_information
      @total = Checkout.pluck(:total).sum
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.role == "admin"
      redirect_to admin_root_path
    else
      redirect_to products_path
    end
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/admin/home/_sidebar.html.erb
<nav class="hidden md:block flex flex-col bg-indigo-700 w-60 min-h-screen text-gray-900 border transition-all border-indigo-900">
  <div class="my-4">
    <ul class="mx-2">
      <%= link_to admin_root_url, method: :get do %>
        <li class="mb-2 px-4 py-4 text-gray-100 flex flex-row items-center border-gray-300 hover:text-black hover:bg-white hover:font-bold rounded rounded-lg">
        <span class="flex items-center">
          <svg class="fill-current h-5 w-5" viewBox="0 0 24 24">
            <path d="M16 20h4v-4h-4m0-2h4v-4h-4m-6-2h4V4h-4m6 4h4V4h-4m-6 10h4v-4h-4m-6 4h4v-4H4m0 10h4v-4H4m6 4h4v-4h-4M4 8h4V4H4v4z"></path>
          </svg>
          <span class="ml-2">Dashboard</span>
        </span>
        </li>
      <% end %>
      <%= link_to admin_orders_path, method: :get do %>
        <li class="mb-2 px-4 py-4 text-gray-100 flex flex-row items-center border-gray-300 hover:text-black hover:bg-white hover:font-bold rounded rounded-lg">
          <span class="flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="fill-current h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
            </svg>
            <span class="ml-2">Order</span>
          </span>
        </li>
      <% end %>
      <%= link_to admin_products_path, method: :get do %>
        <li class="mb-2 px-4 py-4 text-gray-100 flex flex-row items-center border-gray-300 hover:text-black hover:bg-white hover:font-bold rounded rounded-lg">
          <span class="flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
            </svg>
            <span class="ml-2">Product</span>
          </span>
        </li>
      <% end %>
      <%= link_to admin_users_path, method: :get do %>
        <li class="mb-2 px-4 py-4 text-gray-100 flex flex-row items-center border-gray-300 hover:text-black hover:bg-white hover:font-bold rounded rounded-lg">
          <span class="flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
            <span class="ml-2">Manage user</span>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/admin/home/index.html.erb
<div class="flex flex-col w-full">
  <!-- cards -->
  <div class="px-6 pt-8 w-full">
    <div class="grid sm:grid-cols-3 lg:grid-cols-3 gap-4">
      <div class="flex m-auto justify-between w-full items-center bg-indigo-500 p-6">
        <div class="flex rounded-full bg-white border justify-center w-16 h-16">
          <svg class="w-10 h-10 m-auto" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
          </svg>
        </div>
        <div class="flex flex-col text-white text-xl">
          <span><%= @user_count %></span>
          <span>Users</span>
        </div>
      </div>
      <div class="flex m-auto justify-between w-full items-center bg-indigo-500 p-6">
        <div class="flex rounded-full bg-white border justify-center w-16 h-16">
          <svg class="w-10 h-10 m-auto" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
          </svg>
        </div>
        <div class="flex flex-col text-white text-xl">
          <span><%= @product_count %></span>
          <span>Products</span>
        </div>
      </div>
      <div class="flex m-auto justify-between w-full items-center bg-indigo-500 p-6">
        <div class="flex rounded-full bg-white border justify-center w-16 h-16">
          <svg class="w-10 h-10 m-auto" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z" />
          </svg>
        </div>
        <div class="flex flex-col text-white text-xl">
          <span class=""><%= @order_count %></span>
          <span>Orders</span>
        </div>
      </div>
    </div>
  </div>
  <!-- Transactions -->
  <div class="w-full grid grid-cols-1 xl:grid-cols-2 xl:gap-8 my-4 pt-8 px-6">
    <div class="bg-white shadow rounded-lg px-4 sm:pt-6 sm:pb-2 h-full">
      <div class="flex-shrink-0 mb-4">
        <h3 class="text-base font-normal text-gray-500">Total</h3>
        <span class="text-2xl sm:text-3xl leading-none font-bold text-gray-900">
          <%= number_to_currency(@total) %>
        </span>
      </div>
      <%= area_chart Checkout.group_by_day(:created_at).sum(:total) %>
    </div>
    <div class="bg-white shadow rounded-lg px-4 sm:pt-6 sm:pb-2 h-full">
      <div class="mb-4 flex items-center justify-between">
        <div>
          <h3 class="text-xl font-bold text-gray-900 mb-2">Latest Transactions</h3>
        </div>
        <div class="flex-shrink-0">
          <%= link_to "View all", admin_orders_path, class: "text-sm font-medium text-cyan-600 hover:bg-indigo-100 rounded-lg p-2" %>
        </div>
      </div>
      <div class="flex flex-col mt-8">
        <div class="overflow-x-auto rounded-lg">
          <div class="align-middle inline-block min-w-full">
            <div class="shadow overflow-hidden sm:rounded-lg">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-100">
                <tr>
                  <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Transaction
                  </th>
                  <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Created Date
                  </th>
                  <th scope="col" class="p-4 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    Amount
                  </th>
                </tr>
                </thead>
                <tbody class="bg-white">
                  <% @checkouts.each_with_index do |checkout, index| %>
                    <tr class="<%= (index % 2 != 0) ? 'bg-gray-50' : '' %>">
                      <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-900">
                        Payment from <span class="font-semibold"><%= checkout.user.name %></span>
                      </td>
                      <td class="p-4 whitespace-nowrap text-sm font-normal text-gray-500">
                        <%= checkout.created_at.strftime("%B %d, %Y") %>
                      </td>
                      <td class="p-4 whitespace-nowrap text-sm font-semibold text-gray-900">
                        <%= number_to_currency(checkout.total) %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Users and Products -->
  <div class="w-full grid grid-cols-1 xl:grid-cols-2 gap-8 py-8 px-6">
    <!-- Users -->
    <div class="bg-white shadow rounded-lg mb-4 sm:pt-6 sm:pb-2 h-full">
      <div class="flex items-center justify-between mb-4 px-4 sm:px-6">
        <h3 class="text-xl font-bold leading-none text-gray-900">Latest Users</h3>
        <%= link_to "View all", admin_users_path, class: "text-sm font-medium text-cyan-600 hover:bg-indigo-100 rounded-lg inline-flex items-center p-2" %>
      </div>
      <div class="flow-root">
        <ul role="list" class="divide-y divide-gray-200">
          <% @users.each_with_index do |user, index| %>
            <li class="cursor-pointer hover:bg-indigo-50 px-4 sm:px-6 <%= index != @users.size - 1 ? 'py-3 sm:py-4' : 'pt-3 sm:pt-4'  %>" >
              <div class="flex items-center space-x-4">
                <div class="flex-shrink-0">
                  <% if user.image %>
                    <img src="<%= user.image %>" alt="<%= user.gravatar_url %>" class="rounded-full w-10 h-10" />
                  <% else %>
                    <%= image_tag user.gravatar_url, class: "rounded-full w-10 h-10" %>
                  <% end %>
                </div>
                <div class="flex-1 min-w-0">
                  <p class="text-sm font-medium text-gray-900 truncate">
                    <%= user.name %>
                  </p>
                  <p class="text-sm text-gray-500 truncate">
                    <%= user.email %>
                  </p>
                </div>
                <div class="inline-flex items-center text-sm font-semibold text-gray-900">
                  <%= user.created_at.strftime("%B %d, %Y") %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <!-- Products -->
    <div class="bg-white shadow rounded-lg mb-4 pt-4 sm:pt-6 sm:pb-2 h-full">
      <div class="flex items-center justify-between mb-4 px-4 sm:px-6">
        <h3 class="text-xl font-bold leading-none text-gray-900">Latest Products</h3>
        <%= link_to "View all", admin_products_path, class: "text-sm font-medium text-cyan-600 hover:bg-indigo-100 rounded-lg inline-flex items-center p-2" %>
      </div>
      <div class="flow-root">
        <ul role="list" class="divide-y divide-gray-200">
          <% @products.each_with_index do |product, index| %>
            <li class="cursor-pointer hover:bg-indigo-50 px-4 sm:px-6 <%= index != @users.size - 1 ? 'py-3 sm:py-4' : 'pt-3 sm:pt-4'  %>" >
              <%= link_to edit_admin_product_path(product) do %>
                <div class="flex items-center space-x-4">
                <div class="flex-shrink-0">
                  <% if product.image.attached? %>
                    <img src="<%= product.image %>" alt="product" class="w-10 h-10" />
                  <% else %>
                    <img class="w-10 h-10" src="https://images.unsplash.com/photo-1593642632823-8f785ba67e45?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80" alt="">
                  <% end %>
                </div>
                <div class="flex-1 min-w-0">
                  <p class="text-sm font-medium text-gray-900 truncate">
                    <%= product.name %>
                  </p>
                  <p class="text-sm text-gray-500 truncate">
                    <%= number_to_currency(product.price) %>
                  </p>
                </div>
                <div class="inline-flex items-center text-sm font-semibold text-gray-900">
                  <%= product.created_at.strftime("%B %d, %Y") %>
                </div>
              </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>