config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  namespace :admin do
    root "home#index"
    resources :products
    resources :checkouts
    resources :orders
    resources :users
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users
  resources :products do
    resources :reviews
  end
  resources :orders, only: %i[create update destroy]
  resources :line_items, only: %i[create update destroy]
  resources :checkouts, param: :slug
  resource  :cart, only: [:show]
end

app/models/checkout.rb
# frozen_string_literal: true

class Checkout < ApplicationRecord
  belongs_to :user, optional: true
  has_one :order, dependent: :destroy

  before_create :set_slug

  VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  validates :total, presence: true, numericality: { greater_than: 0 }
  validates :name, presence: true
  validates :email, presence: true, length: { in: 5..100 }, format: { with: VALID_EMAIL_REGEX }
  validates :address, presence: true
  validates :phone_number, presence: true

  def to_param
    slug
  end

  def create_charge(token)
    @amount = total * 100.0
    customer = Stripe::Customer.create(
      email: email,
      source: token
    )

    Stripe::Charge.create(
      customer: customer.id,
      amount: trim(@amount),
      description: "user #{email} has started a purchase",
      currency: "usd"
    )
  rescue Stripe::CardError => e
    errors.add(:checkout, e.message)
  end

  private

  def trim(num)
    i = num.to_i
    f = num.to_f
    i == f ? i : f
  end

  def set_slug
    loop do
      self.slug = SecureRandom.hex(10)
      break unless Checkout.exists?(slug: slug)
    end
  end
end

app/controllers/admin/checkouts_controller.rb
# frozen_string_literal: true

module Admin
  class CheckoutsController < ApplicationController
    def index
      @checkouts = Checkout.all
    end

    def update; end
  end
end

app/controllers/checkouts_controller.rb
# frozen_string_literal: true

class CheckoutsController < ApplicationController
  before_action :set_checkout, only: [:show]
  before_action :set_order_and_line_items, only: %i[new create]

  def index
    if current_user
      @checkouts = current_user.checkouts
    else
      redirect_to root_path
      flash[:notice] = "Please login before you proceed"
    end
  end

  def show
    @order = @checkout.order
    @line_items = @order.line_items
  end

  def new
    @checkout = Checkout.new
  end

  def create
    @checkout = Checkout.new(checkout_params)
    return if @order.blank?

    @checkout.user_id = current_user.id if current_user
    update_total
    if @checkout.save
      transaction
    else
      redirect_to new_checkout_path(order_id: @order.id)
      flash[:danger] = "An error occurred. Please try again"
    end
  end

  private

  def set_order_and_line_items
    @order = Order.find_by(id: params[:order_id])
    @line_items = @order.line_items
  end

  def update_total
    @checkout.total = @order.line_items.sum { |line_item| line_item.product.price * line_item.quantity }
  end

  def transaction
    ActiveRecord::Base.transaction do
      finalize_current_order
      finalize_checkout
    end
  end

  def finalize_current_order
    @order.update!(checkout_id: @checkout.id)
    @order.line_items.each do |line_item|
      line_item.update!(unit_price: line_item.product.price, total_price: line_item.product.price * line_item.quantity)
    end
    generate_new_order
  end

  def generate_new_order
    session.delete(:order_id)
    order = current_user ? current_user.orders.build : Order.new
    order.save!
  end

  def finalize_checkout
    session[:checkout_id] = @checkout.id

    if @checkout.create_charge(params[:stripeToken])
      redirect_to @checkout
      flash[:success] = "Your order has been created successfully"
    else
      redirect_to "new"
    end
  end

  def set_checkout
    @checkout = Checkout.find_by(slug: params[:slug])
  end

  def checkout_params
    params.require(:checkout).permit(:name, :email, :address, :phone_number, :order_id)
  end
end

app/views/checkouts/index.html.erb
<% @checkouts.each do |checkout| %>
  <%= link_to checkout_path(checkout) do %>
    <div class="cursor-pointer container m-auto flex flex-col max-w-4xl mt-6 p-4 shadow">
      <div class="flex justify-between">
        <span class="p-2">Order Id: <%= checkout.slug %></span>
        <% case checkout.order.status when 'pending' %>
          <div class="rounded text-blue-400 my-auto">
            <span class="p-6"><%= checkout.order.status %></span>
          </div>
        <% when 'processing' %>
          <div class="rounded text-indigo-600 my-auto">
            <span class="p-6"><%= checkout.order.status %></span>
          </div>
        <% when 'approved' %>
          <div class="rounded text-green-600 my-auto">
            <span class="p-6"><%= checkout.order.status %></span>
          </div>
        <% when 'canceled' %>
          <div class="rounded text-red-600 my-auto">
            <span class="p-6"><%= checkout.order.status %></span>
          </div>
        <% end %>
      </div>
      <span class="p-2">Created at: <%= checkout.created_at %></span>
    </div>
  <% end %>
<% end %>

app/views/checkouts/new.html.erb
<%= form_for @checkout, html: {multipart: true, id: "payment-form"}, validate: true do |form| %>
  <div class="h-screen grid grid-cols-3">
    <div class="lg:col-span-2 col-span-3 bg-indigo-50 space-y-8 px-12">
      <div id="banner" class="mt-8 p-4 relative flex flex-col sm:flex-row sm:items-center bg-white shadow rounded-md">
        <div class="flex flex-row items-center border-b sm:border-b-0 w-full sm:w-auto pb-4 sm:pb-0">
          <div class="text-yellow-500">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 sm:w-5 h-6 sm:h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <div class="text-sm font-medium ml-3">Checkout</div>
        </div>
        <div class="text-sm tracking-wide text-gray-500 mt-4 sm:mt-0 sm:ml-4">
          Please complete your shipping and payment details below.<br/>
          <span class="text-red-700">Use this card info for testing purpose: 4242 4242 4242 4242 -  11/25 - 123 - 55000</span>
        </div>
        <div class="absolute sm:relative sm:top-auto sm:right-auto ml-auto right-4 top-4 text-gray-400 hover:text-gray-800 cursor-pointer">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" onclick="$('#banner').slideUp();">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
        </div>
      </div>
      <div class="rounded-md">
        <h2 class="uppercase tracking-wide text-lg font-semibold text-gray-700 my-2">Shipping & Billing Information</h2>
        <fieldset class="mb-3 bg-white shadow-lg rounded text-gray-600">
          <label class="flex border-b border-gray-200 h-12 py-4 items-center">
            <span class="text-left pl-4 pr-2 w-40">Name</span>
            <%= form.text_field :name, class: "focus:outline-none px-3 w-2/3", value: current_user ? current_user.name : "", required: true %>
          </label>
          <label class="flex border-b border-gray-200 h-12 py-4 items-center">
            <span class="text-left pl-4 pr-2 w-40">Email</span>
            <%= form.email_field :email, class: "focus:outline-none px-3 w-2/3", value: current_user ? current_user.email : "", required: true %>
          </label>
          <label class="flex border-b border-gray-200 h-12 py-4 items-center">
            <span class="text-left pl-4 pr-2 w-40">Address</span>
            <%= form.text_field :address, class: "focus:outline-none px-3 w-2/3", required: true %>
          </label>
          <label class="flex border-b border-gray-200 h-12 py-4 items-center">
            <span class="text-left pl-4 pr-2 w-40">Phone number</span>
            <%= form.text_field :phone_number, class: "focus:outline-none px-3 w-2/3", required: true %>
          </label>
          <div class="flex items-center py-3">
            <span class="text-left pl-4 pr-2 w-40">Card info</span>
            <div class="form-row w-2/3">
              <label for="card-element">
              </label>
              <div id="card-element" class=" items-center">
              </div>
              <div id="card-errors" role="alert"></div>
            </div>
          </div>
        </fieldset>
      </div>
      <%= hidden_field_tag(:order_id, @order.id) %>
      <%= form.submit "Pay", id: "checkout-button", data: { disable_with: "Loading..." }, class: "submit-button cursor-pointer px-4 py-3 rounded-full bg-indigo-400 hover:bg-indigo-500 text-white focus:ring focus:outline-none w-full text-xl font-semibold transition-colors" %>
    </div>
    <div class="col-span-1 bg-white lg:block hidden">
      <h1 class="py-6 border-b-2 text-xl text-gray-600 px-8">Order Summary</h1>
      <ul class="py-6 border-b space-y-6 px-8">
        <% @line_items.each do |line_item| %>
          <li class="grid grid-cols-6 gap-2 border-b-1">
            <div class="col-span-1 self-center">
              <% if line_item.product.image.attached? %>
                <%= image_tag line_item.product.image, class: "rounded w-full" %>
              <% else %>
                <img alt="product-image" class="rounded w-full" src="https://images.unsplash.com/photo-1593642632823-8f785ba67e45?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80">
              <% end %>
            </div>
            <div class="flex flex-col col-span-3 pt-2">
              <span class="text-gray-600 text-md font-semi-bold"><%= line_item.product.name %></span>
              <span class="text-gray-400 text-sm inline-block pt-2"><%= line_item.product.name %></span>
            </div>
            <div class="col-span-2 pt-3">
              <div class="flex items-center space-x-1 text-sm justify-between">
                <span class="text-gray-400"><%= line_item.quantity %> x <%= line_item.product.price %></span>
                <span class="text-indigo-400 font-semibold inline-block"><%= line_item.product.price * line_item.quantity %></span>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
      <div class="px-8 border-b">
        <div class="flex justify-between py-4 text-gray-600">
          <span>Shipping</span>
          <span class="font-semibold text-indigo-500">Free</span>
        </div>
      </div>
      <div class="px-8 border-b pt-8">
        <div class="font-semibold text-xl flex justify-between py-4 text-gray-600 ">
          <span>Subtotal</span>
          <span id="subtotal" class="font-semibold text-indigo-500"><%= number_to_currency(@order.subtotal) %></span>
        </div>
        <div class="font-semibold text-xl flex justify-between py-4 text-gray-600">
          <span>Discount</span>
          <span id="discount-text" class="font-semibold text-indigo-500">0</span>
        </div>
        <div class="font-semibold text-xl flex justify-between py-4 text-gray-600">
          <span>Total</span>
          <span id="total" class="font-semibold text-indigo-500"><%= number_to_currency(@order.subtotal) %></span>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= javascript_pack_tag 'checkout', 'data-turbolinks-track': 'reload' %>

app/views/checkouts/show.html.erb
<div class="container p-8 shadow m-auto mt-6">
  <div class="flex flex-row justify-between">
    <h1>Order Confirmation #<%= @checkout.slug %></h1>
    <span class="text-red"><%= @order.status %></span>
  </div>
  <%= hidden_field_tag @checkout.id %>
  <div>
    <h2>Order summary</h2>
    <div class="py-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table id="checkout-table" class="min-w-full divide-y divide-gray-200">
            <thead class="">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Image
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Quantity
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Unit Price
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Total Price
              </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            <% @line_items.each_with_index do |line_item, index| %>
              <tr>
                <td class="px-6 py-2 whitespace-nowrap">
                  <div class="flex items-center">
                    <div class="flex-shrink-0 h-full w-20">
                      <% if line_item.product.image.attached? %>
                        <%= image_tag line_item.product.image, class: "h-full w-full" %>
                      <% else %>
                        <img class="object-cover object-center max-w-full max-h-full mx-auto" src="https://images.unsplash.com/photo-1593642632823-8f785ba67e45?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80" alt="">
                      <% end %>
                    </div>
                  </div>
                </td>
                <td class="px-6 py-2 whitespace-nowrap">
                  <%= line_item.product.name %>
                </td>
                <td class="px-6 py-2 whitespace-nowrap">
                  <div class="text-sm text-gray-900">
                    <%= line_item.quantity %>
                  </div>
                </td>
                <td class="px-6 py-2 whitespace-nowrap">
                  <div class="text-sm text-gray-900">
                    <%= line_item.unit_price %>
                  </div>
                </td>
                <td class="px-6 py-2 whitespace-nowrap">
                  <div class="text-sm text-gray-900">
                    <%= line_item.total_price %>
                  </div>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>