config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  namespace :admin do
    root "home#index"
    resources :products
    resources :checkouts
    resources :orders
    resources :users
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users
  resources :products do
    resources :reviews
  end
  resources :orders, only: %i[create update destroy]
  resources :line_items, only: %i[create update destroy]
  resources :checkouts, param: :slug
  resource  :cart, only: [:show]
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :line_items, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :rating, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 5 }

  paginates_per 10

  def blank_stars
    5 - rating.to_i
  end

  def update_product_rating
    rating = reviews.sum(:rating) / reviews.size
    update(rating_count: reviews.size, rating: rating)
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  class ProductsController < ApplicationController
    before_action :set_product, only: %i[edit update destroy]

    def index
      @products = Product.with_attached_image.page params[:page]
    end

    def edit; end

    def update
      @product.update(product_params)
      if @product.save
        redirect_to admin_products_path
        flash[:success] = "Updated product successfully"
      else
        redirect_to edit_admin_product_path(@product)
        flash[:danger] = "An error occurred. Please try again"
      end
    end

    def destroy
      @product.image.purge if @product.image.attached?
      @product.destroy
      redirect_to request.referer || admin_products_url
      flash[:success] = "Products has been deleted successfully"
    end

    private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :rating, :image)
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :valid_user,  only: %i[edit update destroy]

  def index
    @products = Product.all
    @line_item = current_order.line_items.new
  end

  def show
    @line_item = current_order.line_items.new
    @review = Review.new
  end

  def new
    @product = Product.new
    @line_item = current_order.line_items.new
  end

  def create
    @product = current_user.products.build(product_params)
    if @product.save
      redirect_to product_path(@product)
      flash[:success] = "Created product successfully"
    else
      redirect_to new_product_path
      flash[:danger] = "An error occurred. Please try again"
    end
  end

  def edit; end

  def update
    @product.update(product_params)
    if @product.save
      redirect_to user_path(current_user)
      flash[:success] = "Updated user successfully"
    else
      redirect_to edit_product_path(@product)
      flash[:danger] = "An error occurred. Please try again"
    end
  end

  def destroy
    @product.image.purge if @product.image.attached?
    @product.destroy
    redirect_to request.referer || products_path
    flash[:success] = "Deleted product successfully"
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def valid_user
    redirect_to root_path if @product.user_id != current_user.id
  end

  def product_params
    params.require(:product).permit(:name, :price, :description, :image, :rating)
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def time_since(utc)
    DateTime.parse(utc.to_s).strftime("%I:%M %p")
  end
end

app/views/products/_comment_form.html.erb
<%= form_for [@product, @review], remote: true do |form| %>
  <div class="flex flex-wrap -mx-3 mb-6">
    <h2 class="px-4 pt-3 pb-2 text-gray-6 text-lg">Write your review</h2>
    <div class="w-full md:w-full flex px-3 mb-2 mt-2 w-6 h-6" id="star">
      <%= form.hidden_field :rating, id: :review_star, class: "flex" %>
    </div>
    <div class="w-full md:w-full px-3 mb-2 mt-2">
      <%= form.text_area :content, {id: "comment-content", class: "rounded border border-gray-400 leading-normal resize-none w-full h-20 py-2 px-3 font-medium placeholder-gray-400 focus:outline-none focus:bg-white", placeholder: "Write your comment", require: true } %>
    </div>
    <div class="w-full md:w-full flex items-start md:w-full px-3">
      <% if user_signed_in? %>
        <div class="-mr-1">
          <%= form.submit "Post", method: :post, class: "cursor-pointer bg-white text-gray-700 font-medium py-1 px-4 border border-gray-400 rounded-lg tracking-wide mr-1 hover:bg-indigo-400 hover:text-white" %>
        </div>
      <% else %>
        <%= link_to "Please login to use this feature", new_user_session_path, class: "text-gray-700 underline" %>
      <% end %>
    </div>
  </div>
<% end %>
<script>
    $(document).ready(function() {
        let star = $('#star')
        star.raty({
            size     : 10,
            starOff  : '<%= image_path "star-off.svg" %>',
            starOn   : '<%= image_path "star-on.svg" %>',
            scoreName: 'review[rating]',
            half     : false,
        });
        star.raty.reload();
    });
</script>

app/views/products/_comment_section.html.erb
<% @product.reviews.each_with_index do |review, index| %>
  <div class="flex pb-8">
    <div class="flex-shrink-0 mr-3">
      <% if review.user.image %>
        <img src="<%= review.user.image %>" alt="<%= review.user.gravatar_url %>" class="mt-2 rounded-full w-8 h-8 sm:w-10 sm:h-10" />
      <% else %>
        <%= image_tag review.user.gravatar_url, class: "mt-2 rounded-full w-8 h-8 sm:w-10 sm:h-10" %>
      <% end %>
    </div>
    <div class="flex-1 border border-gray-400 rounded-lg px-4 py-2 sm:px-6 sm:py-4 leading-relaxed">
      <div class="mb-px">
        <strong class="mr-2"><%= review.user.name %></strong><span class="text-xs text-gray-400"><%= time_since(review.updated_at) %></span>
      </div>
      <div id="comment-rating-<%= index %>" class="flex flex-row h-4 w-4 mb-2"></div>
      <p class="text-sm">
        <%= review.content %>
      </p>
      <% if current_user.id == review.user_id %>
        <div class="flex-1 pt-2">
          <%= link_to "Edit", edit_product_review_path(@product, review), class: "text-sm font-medium text-indigo-700 border-r-2 border-gray-400 pr-1" %>
          <%= link_to "Delete", product_review_path(@product, review), method: :delete, remote: true, class: "text-sm font-medium text-red-700" %>
        </div>
      <% end %>
    </div>
  </div>
  <script>
      $('#comment-rating-<%= index %>').raty({
          size     : 10,
          starOff: '<%= image_path "star-off.svg" %>',
          starOn : '<%= image_path "star-on.svg" %>',
          half: false,
          readOnly: true,
          score: <%= review.rating %>,
      });
      $('#comment-rating-<%= index %>').raty.reload();
  </script>
<% end %>

app/views/products/_form.html.erb
<%= form_for @product, class: "form" do |form| %>
  <div class="heading text-center font-bold text-2xl m-5 text-gray-800">New Product</div>
  <div class="editor rounded-md shadow-md mx-auto w-10/12 flex flex-col text-gray-800 p-4 shadow-lg max-w-8xl">
    <div class="grid grid-cols-3">
      <!-- image -->
      <div id="preview-image-holder" class="py-12 mr-8 h-60 flex flex-col justify-center items-center" style="display: none">
        <%= image_tag 'default-image.svg', alt: 'icon', id: "preview-image", class: "max-w-full h-full m-auto" %>
      </div>
      <div class="border-dashed border-2 border-gray-400 py-12 mr-8 h-full flex flex-col justify-center items-center" id="form-uploader">
        <p class="p-4 font-semibold text-gray-900 flex flex-wrap justify-center">
          <span class="text-center break-word">Drag and drop your files anywhere or</span>
        </p>
        <input id="hidden-input" type="file" multiple class="hidden z-10" />
        <label id="food-image-label" class="mt-2 rounded-sm px-3 py-1 bg-gray-200 hover:bg-indigo-500 cursor-pointer hover:text-white focus:shadow-outline focus:outline-none">
          Upload a file
          <%= form.file_field :image, class: "hidden absolute", id: "uploader" %>
        </label>
      </div>
      <div class="col-span-2">
        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name, {class: "title border border-gray-300 w-full p-2 mb-4 outline-none", placeholder: "name"} %>
        </div>
        <div class="field">
          <%= form.label :description %>
          <%= form.text_area :description, {class: "title border border-gray-300 w-full p-2 mb-4 outline-none", placeholder: "description"} %>
        </div>
        <div class="field">
          <%= form.label :price %>
          <%= form.number_field :price, {class: "title border border-gray-300 w-full p-2 mb-4 outline-none", placeholder: "price", min: 0.0, step: 0.01} %>
        </div>
        <%= form.number_field :rating, {class: "title border border-gray-300 w-full p-2 mb-4 outline-none", placeholder: "default rating", min: 0.0, step: 0.1} %>
      </div>
    </div>
    <!-- buttons -->
    <div class="buttons flex">
      <div class="btn border border-gray-300 p-1 px-4 font-semibold cursor-pointer text-gray-500 ml-auto">Cancel</div>
      <%= form.submit "Create", method: :post, class: "btn border border-indigo-500 p-1 px-4 font-semibold cursor-pointer text-gray-200 ml-2 bg-indigo-500" %>
    </div>
  </div>
<% end %>
<%= javascript_pack_tag 'image', 'data-turbolinks-track': 'reload' %>

app/views/products/_product_list.html.erb
<% @products.each_with_index do |item, index| %>
  <%= form_for @line_item, remote: true do |form| %>
    <div class="w-full max-w-sm mx-auto rounded-md shadow-md overflow-hidden cursor-pointer">
      <a class="block relative h-40 rounded overflow-hidden">
        <% if item.image.attached? %>
          <%= image_tag item.image, class: "object-cover object-center max-w-full max-h-full mx-auto" %>
        <% else %>
          <img class="object-cover object-center max-w-full max-h-full mx-auto" src="https://images.unsplash.com/photo-1593642632823-8f785ba67e45?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80" alt="">
      <% end %>
      </a>
      <div class="px-5 py-3">
        <h2 class="text-gray-900 title-font text-lg font-medium"><%= item.name %></h2>
        <div class="flex items-center mt-1">
          <svg class="mr-1 w-5 h-5 fill-current text-yellow-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M10 15l-5.878 3.09 1.123-6.545L.489 6.91l6.572-.955L10 0l2.939 5.955 6.572.955-4.756 4.635 1.123 6.545z"/></svg>
          <%= item.rating %>
        </div>
        <p class="mt-1">$<%= item.price %></p>
        <div class="flex mt-2 justify-between">
          <%= form.number_field :quantity, value: 1, class: "hidden" %>
          <%= form.hidden_field :product_id, value: item.id %>
          <%= form.submit "Add to cart", class: "cursor-pointer w-full p-1 bg-indigo-600 text-white"  %>
          <%= link_to "Detail", product_path(item.id), class: "w-full p-1 bg-gray-600 text-white text-center", method: :get %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<%= render 'products/form' %>

app/views/products/index.html.erb
<div class="flex">
  <div class="container px-5 py-20 mx-auto">
    <div class="grid gap-14 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 mt-6">
      <%= render 'products/product_list' %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<%= form_for @product, class: "form" do |form| %>

  <div class="heading text-center font-bold text-2xl m-5 text-gray-800">New Product</div>
  <div class="editor rounded-md shadow-md mx-auto w-10/12 flex flex-col text-gray-800 p-4 shadow-lg max-w-8xl">
    <div class="grid grid-cols-3">
      <!-- image -->
      <div id="preview-image-holder" class="py-12 mr-8 h-60 flex flex-col justify-center items-center" style="display: none">
        <%= image_tag 'default-image.svg', alt: 'icon', id: "preview-image", class: "max-w-full h-full m-auto" %>
      </div>
      <div class="border-dashed border-2 border-gray-400 py-12 mr-8 h-60 flex flex-col justify-center items-center" id="form-uploader">
        <p class="p-4 font-semibold text-gray-900 flex flex-wrap justify-center">
          <span class="text-center break-word">Drag and drop your files anywhere or</span>
        </p>
        <input id="hidden-input" type="file" multiple class="hidden z-10" />
        <label id="food-image-label" class="mt-2 rounded-sm px-3 py-1 bg-gray-200 hover:bg-indigo-500 cursor-pointer hover:text-white focus:shadow-outline focus:outline-none">
          Upload a file
          <%= form.file_field :image, class: "hidden absolute", id: "uploader" %>
        </label>
      </div>
      <div class="col-span-2">
        <%= form.text_field :name, {class: "title border border-gray-300 w-full p-2 mb-4 outline-none", placeholder: "name"} %>
        <%= form.text_area :description, {class: "title border border-gray-300 w-full p-2 mb-4 outline-none", placeholder: "description"} %>
        <%= form.number_field :price, {class: "title border border-gray-300 w-full p-2 mb-4 outline-none", placeholder: "price", min: 0} %>
        <%= form.number_field :rating, {class: "title border border-gray-300 w-full p-2 mb-4 outline-none", placeholder: "default rating", min: 0.0, step: 0.1} %>

      </div>
    </div>
    <!-- buttons -->
    <div class="buttons flex">
      <div class="btn border border-gray-300 p-1 px-4 font-semibold cursor-pointer text-gray-500 ml-auto">Cancel</div>
      <%= form.submit "Create", method: :post, class: "btn border border-indigo-500 p-1 px-4 font-semibold cursor-pointer text-gray-200 ml-2 bg-indigo-500" %>
    </div>
  </div>
<% end %>
<%= javascript_pack_tag 'image', 'data-turbolinks-track': 'reload' %>

app/views/products/show.html.erb
<div class="text-gray-700 body-font overflow-hidden bg-white">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <% if @product.image.attached? %>
        <div class="flex lg:w-1/2 w-full object-cover object-center rounded border border-gray-200">
          <%= image_tag @product.image, class: "w-full h-full m-auto"%>
        </div>
      <% else %>
        <div class="flex lg:w-1/2 w-full object-cover object-center rounded border border-gray-200">
          <img class="w-full h-full m-auto" src="https://images.unsplash.com/photo-1593642632823-8f785ba67e45?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80" alt="">
        </div>
      <% end %>
      <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-2"><%= @product.name %></h1>
        <div class="flex mb-4">
          <span class="flex items-center">
            <% @product.rating.to_i.times do %>
              <%= image_tag "star-on.svg", class: "w-6 h-6" %>
            <% end %>
            <% @product.blank_stars.times do %>
              <%= image_tag "star-off.svg", class: "w-6 h-6" %>
            <% end %>
            <span class="text-gray-600 ml-3"><%= @product.reviews.count %> Reviews</span>
          </span>
        </div>
        <p class="leading-relaxed"><%= @product.description %></p>
        <%= form_for @line_item, remote: true, html: {id: "add-to-cart-form"} do |form| %>
          <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-200 mb-5">
            <div class="flex items-center">
              <span class="bold-800 mr-3">Quantity</span>
              <div class="relative">
                <%= form.hidden_field :product_id, value: @product.id %>
                <%= form.number_field :quantity, { class: "rounded border appearance-none border-gray-400 w-20 py-2 focus:outline-none focus:border-indigo-500 text-base pl-3 pr-1", min: 1, value: 1} %>
              </div>
            </div>
          </div>
          <div class="flex">
            <span class="title-font font-medium text-2xl text-gray-900">$<%= @product.price %></span>
            <%= form.submit "Add to cart", class: "flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 cursor-pointer focus:outline-none hover:bg-indigo-600 rounded" %>
          </div>
        <% end %>
      </div>
    </div>
    <div id="comment-form" class="lg:w-4/5 mx-auto rounded-lg pt-6">
      <%= render 'products/comment_form' %>
    </div>
    <div id="comment-section" class="flex flex-col lg:w-4/5 mx-auto pt-6">
      <%= render 'products/comment_section' %>
    </div>
  </div>
</div>